/**
 * A packet envelope can NEVER point at a Docuseal template.
 *
 * Brian's ruling after the A6b finding. The static template
 * (SOTO_Legal_Text_Package_FINAL_v3) was a first-boot artifact: one PDF of the
 * whole legal package — Master + all five Schedules + BOTH §7216 consent forms —
 * with a single signature. Sending it would mean a tax-only client physically
 * accepting bookkeeping and entity terms the database says they never accepted,
 * and §7216 consent captured by the same signature that engages the service.
 *
 * The packet document is now generated by SAOS per client. This makes the old
 * shape UNREPRESENTABLE rather than merely discouraged: an envelope marked as a
 * packet envelope cannot carry a docuseal_template_id, enforced by a plain CHECK
 * (no trigger — it is a single-row invariant).
 */

exports.up = (pgm) => {
  pgm.sql(`
    ALTER TABLE signature_envelopes
      ADD COLUMN is_packet_envelope boolean NOT NULL DEFAULT false,
      ADD CONSTRAINT signature_envelopes_packet_never_templated CHECK (
        NOT (is_packet_envelope AND docuseal_template_id IS NOT NULL)
      );

    COMMENT ON COLUMN signature_envelopes.is_packet_envelope IS
      'TRUE = carries a SAOS-generated Master+Schedules packet. Such an envelope may never reference a Docuseal template: the static all-in-one template bundled schedules a client had not engaged and the §7216 consents, which must be presented separately after signature.';
  `);
};

exports.down = (pgm) => {
  pgm.sql(`
    ALTER TABLE signature_envelopes
      DROP CONSTRAINT signature_envelopes_packet_never_templated,
      DROP COLUMN is_packet_envelope;
  `);
};
